### ISSUE TITLE
Error on registration at pipedot.org

### ISSUE THREAD

**Issue by TheCycoONE** [pipedot/pipecode#4]
After filling in my user details on the registration form, I got the following error in my browser:
error: sql [select * from email_challenge where code = ?] arg [8bf56c2695fbaf510cf08b63fbc0cde41ecbaa67e37e0a2dc24d637a28c77778] msg [SQLSTATE[42S22]: Column not found: 1054 Unknown column 'code' in 'where clause']

**Comment by zenbi** [comment]
Thank you for the report! Should be fixed now.
